### ISSUE TITLE
Integrate alert/confirm modal helpers 

### ISSUE THREAD

**Issue by lgavillet** [at-point/mtl#93]
Integrate alert/confirm modal helpers into the app. Goal is to redefine the default browser dialogs in the MTL namespace, which should be semantically the same. Sadly, active waiting isn't possible... Question is how to handle the callbacks? 
a. The method returns a Promise?  https://promisesaplus.com/
b. ~~Methods arguments accepts callbacks in options, such as: `{ success: -> ..., cancel: -> ... }`~~

Example: 
```javascript
alert('hello');
MTL.alert('its me');
confirm('I was wondering if after all these years youd like to meet ');
MTL.confirm('to go over everything?');
```

The MTL.alert should display the following 
<img width="885" alt="screen shot 2017-03-15 at 07 57 55" src="https://cloud.githubusercontent.com/assets/3090221/23936938/1fa41454-0955-11e7-9c22-2769813e25ba.png">

Same goes for confirm(). 

#### Additional options
As an added value, methods should accept an option hash to configure the look & feel of the modal. 

##### Alert
__Method__ alert(message, options = {})
__Arguments__
- message - The message to display, as is in the default behaviour
- options *optional* - an options hash, for the following values
   - title *optional* - The modal title. Defaults to null (not shown)
   - button *optional* - Button text. Defaults to 'OK'

##### Confirm
__Method__ confirm(message, options = {})
__Arguments__
- message - The message to display, as is in the default behaviour
- options *optional* - an options hash, for the following values
   - title *optional* - The modal title. Defaults to null (not shown)
   - confirmButton *optional* - Confirm button text. Defaults to 'OK'
   - cancelButton *optional* - Cancel button text. Defaults to 'Cancel'

#### 🔧 Tasks/open points
- [x] Define the callback solution -> Promises
- [ ] Integrate the proper helpers, according to the above documentation 
- [ ] Provide a solution to override the default methods provided by Rails and use those dialogs instead. Should be non-destructive, so only as an option and available when activated. 

@sled @philiplehmann inputs?

**Comment by philiplehmann** [comment]
i would use promises but we would need a polyfill for internet explorer 11. with promises its easy to chain tasks

**Comment by philiplehmann** [comment]
we would have to overwrite $.rails.confirm and some functions using $.rails.confirm to archive that
https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L87

we would have to supply our own jquery_ujs with mtl which could get included instead of the rails version:
https://github.com/at-point/cam/blob/master/app/assets/javascripts/admin/application.js#L16
to
maybe best with the rails version...
`//= require mtl/jquery_ujs_5.0.0`

**Comment by lgavillet** [comment]
Promises -> Agreed

**Comment by lgavillet** [comment]
Not a fan of overriding the jquery_ujs, should be simple enough to overload/rewrite the eventhandlers. Also discussed with @sled

**Comment by philiplehmann** [comment]
yeah he has way the better method 😃
